runtime: nodejs10
env: standard

automatic_scaling:
  max_instances: 4
  target_cpu_utilization: 0.7

inbound_services:
- warmup

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto