runtime: nodejs10
env: standard

automatic_scaling:
  max_instances: 4
  target_cpu_utilization: 0.7

handlers:
  - url: /static
    static_dir: public

  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto