runtime: nodejs12
env: standard

automatic_scaling:
  max_instances: 2
  target_cpu_utilization: 0.7

handlers:
- url: /privacy
  static_dir: public/privacy

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto