substitutions:
    _APP_NAME: talk-service
    _CONFIG_FILE: 'infrastructure/deployment.yaml'
steps:
# Enable deployment manager (if needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['services', 'enable', 'deploymentmanager.googleapis.com']
# Deploy/Update related infrastructure
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: ['infrastructure/cloudbuild.sh', '$_APP_NAME', '$_CONFIG_FILE']
# Update dependencies
  - name: node
    entrypoint: npm
    args: ['install']
# Run tests
  - name: node
    entrypoint: npm
    args: ['test']
# Deploy app 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']