substitutions:
    _APP_NAME: talk-service
steps:
# Enable deployment manager (if needed)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['services', 'enable', 'deploymentmanager.googleapis.com']
# Deploy/Update related infrastructure
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['deployment-manager', 'deployments', 'create', '$_APP_NAME', '--config', 'infrastructure/deployment.yaml']
# Update dependencies
  - name: node
    entrypoint: npm
    args: ['install']
# Run tests
  - name: node
    entrypoint: npm
    args: ['test']
# Deploy app 
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']